"""feat: products domain 7 tables

Revision ID: 3d49919fb143
Revises: f5daa856cf4b
Create Date: 2026-04-12 21:00:32.403061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3d49919fb143'
down_revision: Union[str, None] = 'f5daa856cf4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.UUID(), nullable=False, comment='主键 (UUID v7)'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='分类名称'),
    sa.Column('parent_id', sa.UUID(), nullable=True, comment='父分类 ID'),
    sa.Column('icon_url', sa.String(length=500), nullable=True, comment='分类图标 URL'),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='排序权重（越大越前）'),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='是否启用'),
    sa.Column('level_prices', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='分类级等级折扣率 [{"level_id":"uuid","discount_rate":0.95}]'),
    sa.Column('level_commissions', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='分类级等级百分比分佣 [{"level_id":"uuid","first_rate":0.03,...}]'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间 (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间 (UTC)'),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], name=op.f('fk_categories_parent_id_categories'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories'))
    )
    op.create_table('products',
    sa.Column('id', sa.UUID(), nullable=False, comment='主键 (UUID v7)'),
    sa.Column('name', sa.String(length=200), nullable=False, comment='商品标题'),
    sa.Column('subtitle', sa.String(length=500), nullable=True, comment='副标题/卖点'),
    sa.Column('product_type', sa.String(length=20), nullable=False, comment='商品类型: virtual / physical'),
    sa.Column('main_image', sa.String(length=500), nullable=False, comment='商品主图 URL'),
    sa.Column('images', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=True, comment='轮播图 URL 数组'),
    sa.Column('description', sa.Text(), nullable=True, comment='商品详情（富文本）'),
    sa.Column('market_price', sa.Numeric(precision=15, scale=2), nullable=False, comment='市场价（划线价）'),
    sa.Column('base_price', sa.Numeric(precision=15, scale=2), nullable=False, comment='本店售价'),
    sa.Column('cost_price', sa.Numeric(precision=15, scale=2), nullable=True, comment='成本价（无 SKU 时使用）'),
    sa.Column('stock', sa.Integer(), nullable=True, comment='库存（无 SKU 时使用）'),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'draft'"), nullable=False, comment='上架状态: draft / on_sale / off_sale'),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='排序权重'),
    sa.Column('sales_count', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='累计销量'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间 (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间 (UTC)'),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='是否软删除'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='删除时间 (UTC)'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products'))
    )
    op.create_table('product_categories',
    sa.Column('id', sa.UUID(), nullable=False, comment='主键 (UUID v7)'),
    sa.Column('product_id', sa.UUID(), nullable=False, comment='商品 ID'),
    sa.Column('category_id', sa.UUID(), nullable=False, comment='分类 ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间 (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间 (UTC)'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_product_categories_category_id_categories'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_categories_product_id_products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_categories')),
    sa.UniqueConstraint('product_id', 'category_id', name='uq_product_category')
    )
    op.create_table('product_level_commissions',
    sa.Column('id', sa.UUID(), nullable=False, comment='主键 (UUID v7)'),
    sa.Column('product_id', sa.UUID(), nullable=False, comment='归属商品 ID'),
    sa.Column('level_id', sa.UUID(), nullable=False, comment='推荐人等级 ID'),
    sa.Column('commission_first', sa.Numeric(precision=15, scale=2), nullable=False, comment='直推佣金固定金额'),
    sa.Column('commission_second', sa.Numeric(precision=15, scale=2), server_default=sa.text('0.00'), nullable=False, comment='间推佣金固定金额'),
    sa.Column('commission_other', sa.Numeric(precision=15, scale=2), server_default=sa.text('0.00'), nullable=False, comment='其它层级佣金固定金额'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间 (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间 (UTC)'),
    sa.ForeignKeyConstraint(['level_id'], ['user_levels.id'], name=op.f('fk_product_level_commissions_level_id_user_levels'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_level_commissions_product_id_products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_level_commissions')),
    sa.UniqueConstraint('product_id', 'level_id', name='uq_product_level_commission')
    )
    op.create_table('product_skus',
    sa.Column('id', sa.UUID(), nullable=False, comment='主键 (UUID v7)'),
    sa.Column('product_id', sa.UUID(), nullable=False, comment='归属商品 ID'),
    sa.Column('sku_code', sa.String(length=100), nullable=False, comment='SKU 唯一编码'),
    sa.Column('spec_values', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='规格组合 {"颜色":"红色","尺寸":"XL"}'),
    sa.Column('price', sa.Numeric(precision=15, scale=2), nullable=False, comment='SKU 独立售价'),
    sa.Column('cost_price', sa.Numeric(precision=15, scale=2), nullable=True, comment='成本价'),
    sa.Column('stock', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='库存数量'),
    sa.Column('image_url', sa.String(length=500), nullable=True, comment='SKU 专属图片'),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='是否启用'),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='显示顺序'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间 (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间 (UTC)'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_skus_product_id_products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_skus')),
    sa.UniqueConstraint('sku_code', name=op.f('uq_product_skus_sku_code'))
    )
    op.create_index(op.f('ix_product_skus_product_skus_product_id'), 'product_skus', ['product_id'], unique=False)
    op.create_table('product_specs',
    sa.Column('id', sa.UUID(), nullable=False, comment='主键 (UUID v7)'),
    sa.Column('product_id', sa.UUID(), nullable=False, comment='归属商品 ID'),
    sa.Column('spec_name', sa.String(length=50), nullable=False, comment='规格名称（如颜色、尺寸）'),
    sa.Column('spec_values', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='候选值数组 ["红色","蓝色","白色"]'),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='展示顺序'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间 (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间 (UTC)'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_specs_product_id_products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_specs')),
    sa.UniqueConstraint('product_id', 'spec_name', name='uq_product_spec_name')
    )
    op.create_table('product_level_prices',
    sa.Column('id', sa.UUID(), nullable=False, comment='主键 (UUID v7)'),
    sa.Column('product_id', sa.UUID(), nullable=False, comment='归属商品 ID'),
    sa.Column('sku_id', sa.UUID(), nullable=True, comment='指定 SKU（null = 商品级）'),
    sa.Column('level_id', sa.UUID(), nullable=False, comment='会员等级 ID'),
    sa.Column('price', sa.Numeric(precision=15, scale=2), nullable=False, comment='该等级的固定售价'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间 (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间 (UTC)'),
    sa.ForeignKeyConstraint(['level_id'], ['user_levels.id'], name=op.f('fk_product_level_prices_level_id_user_levels'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_level_prices_product_id_products'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sku_id'], ['product_skus.id'], name=op.f('fk_product_level_prices_sku_id_product_skus'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_level_prices')),
    sa.UniqueConstraint('product_id', 'sku_id', 'level_id', name='uq_product_sku_level_price')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_level_prices')
    op.drop_table('product_specs')
    op.drop_index(op.f('ix_product_skus_product_skus_product_id'), table_name='product_skus')
    op.drop_table('product_skus')
    op.drop_table('product_level_commissions')
    op.drop_table('product_categories')
    op.drop_table('products')
    op.drop_table('categories')
    # ### end Alembic commands ###
