"""add invite_code invited_at to user_level_profiles

Revision ID: df16ff406d52
Revises: 375d749c574a
Create Date: 2026-04-13 14:10:06.185261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df16ff406d52'
down_revision: Union[str, None] = '375d749c574a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_level_profiles', sa.Column('invite_code', sa.String(length=20), nullable=True, comment='用户专属邀请码'))
    op.add_column('user_level_profiles', sa.Column('invited_at', sa.String(length=30), nullable=True, comment='被邀请绑定时间'))
    op.create_index(op.f('ix_user_level_profiles_user_level_profiles_inviter_id'), 'user_level_profiles', ['inviter_id'], unique=False)
    op.create_unique_constraint(op.f('uq_user_level_profiles_invite_code'), 'user_level_profiles', ['invite_code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_user_level_profiles_invite_code'), 'user_level_profiles', type_='unique')
    op.drop_index(op.f('ix_user_level_profiles_user_level_profiles_inviter_id'), table_name='user_level_profiles')
    op.drop_column('user_level_profiles', 'invited_at')
    op.drop_column('user_level_profiles', 'invite_code')
    # ### end Alembic commands ###
