"""feat: user wallets and logs

Revision ID: f5daa856cf4b
Revises: 51c0e1e84482
Create Date: 2026-04-12 19:46:09.866963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5daa856cf4b'
down_revision: Union[str, None] = '51c0e1e84482'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_balance_logs',
    sa.Column('id', sa.UUID(), nullable=False, comment='主键 (UUID v7)'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='归属用户ID'),
    sa.Column('change_type', sa.String(length=50), nullable=False, comment='变动类型(如order_pay/commission_first)'),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False, comment='变动金额(+/-)'),
    sa.Column('before_balance', sa.Numeric(precision=15, scale=2), nullable=False, comment='变动前余额'),
    sa.Column('after_balance', sa.Numeric(precision=15, scale=2), nullable=False, comment='变动后余额'),
    sa.Column('ref_id', sa.UUID(), nullable=True, comment='关联的业务单据ID'),
    sa.Column('remark', sa.String(length=255), nullable=True, comment='变动备注/原因说明'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间 (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间 (UTC)'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_balance_logs_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_balance_logs'))
    )
    op.create_index(op.f('ix_user_balance_logs_user_balance_logs_change_type'), 'user_balance_logs', ['change_type'], unique=False)
    op.create_index(op.f('ix_user_balance_logs_user_balance_logs_ref_id'), 'user_balance_logs', ['ref_id'], unique=False)
    op.create_index(op.f('ix_user_balance_logs_user_balance_logs_user_id'), 'user_balance_logs', ['user_id'], unique=False)
    op.create_table('user_point_logs',
    sa.Column('id', sa.UUID(), nullable=False, comment='主键 (UUID v7)'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='归属用户ID'),
    sa.Column('change_type', sa.String(length=50), nullable=False, comment='变动类型(如sign_in/order_complete)'),
    sa.Column('points', sa.Integer(), nullable=False, comment='变动积分(+/-)'),
    sa.Column('before_points', sa.Integer(), nullable=False, comment='变动前积分'),
    sa.Column('after_points', sa.Integer(), nullable=False, comment='变动后积分'),
    sa.Column('ref_id', sa.UUID(), nullable=True, comment='关联的业务单据ID'),
    sa.Column('remark', sa.String(length=255), nullable=True, comment='变动备注/原因说明'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间 (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间 (UTC)'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_point_logs_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_point_logs'))
    )
    op.create_index(op.f('ix_user_point_logs_user_point_logs_change_type'), 'user_point_logs', ['change_type'], unique=False)
    op.create_index(op.f('ix_user_point_logs_user_point_logs_ref_id'), 'user_point_logs', ['ref_id'], unique=False)
    op.create_index(op.f('ix_user_point_logs_user_point_logs_user_id'), 'user_point_logs', ['user_id'], unique=False)
    op.create_table('user_wallets',
    sa.Column('id', sa.UUID(), nullable=False, comment='主键 (UUID v7)'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='归属用户ID'),
    sa.Column('balance', sa.Numeric(precision=15, scale=2), nullable=False, comment='当前可用现金余额'),
    sa.Column('frozen_balance', sa.Numeric(precision=15, scale=2), nullable=False, comment='提现审核等冻结的余额'),
    sa.Column('points', sa.Integer(), nullable=False, comment='当前可用总积分'),
    sa.Column('version', sa.Integer(), nullable=False, comment='乐观锁版本号'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间 (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间 (UTC)'),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='是否软删除'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='删除时间 (UTC)'),
    sa.CheckConstraint('balance >= 0', name=op.f('ck_user_wallets_ck_wallet_balance_positive')),
    sa.CheckConstraint('frozen_balance >= 0', name=op.f('ck_user_wallets_ck_wallet_frozen_positive')),
    sa.CheckConstraint('points >= 0', name=op.f('ck_user_wallets_ck_wallet_points_positive')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_wallets_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_wallets')),
    sa.UniqueConstraint('user_id', name=op.f('uq_user_wallets_user_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_wallets')
    op.drop_index(op.f('ix_user_point_logs_user_point_logs_user_id'), table_name='user_point_logs')
    op.drop_index(op.f('ix_user_point_logs_user_point_logs_ref_id'), table_name='user_point_logs')
    op.drop_index(op.f('ix_user_point_logs_user_point_logs_change_type'), table_name='user_point_logs')
    op.drop_table('user_point_logs')
    op.drop_index(op.f('ix_user_balance_logs_user_balance_logs_user_id'), table_name='user_balance_logs')
    op.drop_index(op.f('ix_user_balance_logs_user_balance_logs_ref_id'), table_name='user_balance_logs')
    op.drop_index(op.f('ix_user_balance_logs_user_balance_logs_change_type'), table_name='user_balance_logs')
    op.drop_table('user_balance_logs')
    # ### end Alembic commands ###
