"""feat/security: 挂载全视图防盗审计基础表 (LoginLog & AuditLog)

Revision ID: 5b633cf25059
Revises: 2b82e56e8e94
Create Date: 2026-04-11 23:56:01.819836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5b633cf25059'
down_revision: Union[str, None] = '2b82e56e8e94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sys_audit_logs',
    sa.Column('id', sa.UUID(), nullable=False, comment='主键 (UUID v7)'),
    sa.Column('actor_type', sa.String(length=20), nullable=False, comment='身份集: user|admin'),
    sa.Column('actor_id', sa.String(length=36), nullable=True, comment='目标标识'),
    sa.Column('module', sa.String(length=50), nullable=False, comment='操作模块 (如: finance)'),
    sa.Column('action', sa.String(length=100), nullable=False, comment='核心动词 (如: refund)'),
    sa.Column('endpoint', sa.String(length=255), nullable=True, comment='网络层:API端点'),
    sa.Column('method', sa.String(length=10), nullable=True, comment='网络层:请求方法'),
    sa.Column('ip_address', sa.String(length=50), nullable=True, comment='发起者IP'),
    sa.Column('request_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='请求快照包裹'),
    sa.Column('response_status', sa.Integer(), nullable=True, comment='服务器返回响应码'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间 (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间 (UTC)'),
    sa.CheckConstraint("actor_type IN ('user', 'admin')", name=op.f('ck_sys_audit_logs_ck_auditlog_actortype_valid')),
    sa.CheckConstraint("request_payload IS NULL OR jsonb_typeof(request_payload) = 'object' OR jsonb_typeof(request_payload) = 'array'", name=op.f('ck_sys_audit_logs_ck_auditlog_payload_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sys_audit_logs'))
    )
    op.create_index('ix_auditlog_module_action', 'sys_audit_logs', ['module', 'action'], unique=False)
    op.create_table('sys_login_logs',
    sa.Column('id', sa.UUID(), nullable=False, comment='主键 (UUID v7)'),
    sa.Column('actor_type', sa.String(length=20), nullable=False, comment='身份集: user|admin'),
    sa.Column('actor_id', sa.String(length=36), nullable=True, comment='目标标识'),
    sa.Column('ip_address', sa.String(length=50), nullable=True, comment='来源IP'),
    sa.Column('user_agent', sa.String(length=255), nullable=True, comment='请求端指纹'),
    sa.Column('status', sa.Boolean(), nullable=False, comment='是否发放 Token 成功'),
    sa.Column('reason', sa.String(length=255), nullable=True, comment='判定明细(如: 密码错误, CAPTCHA拦截)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间 (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间 (UTC)'),
    sa.CheckConstraint("actor_type IN ('user', 'admin')", name=op.f('ck_sys_login_logs_ck_loginlog_actortype_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sys_login_logs'))
    )
    op.create_index('ix_loginlog_actor_status', 'sys_login_logs', ['actor_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_loginlog_actor_status', table_name='sys_login_logs')
    op.drop_table('sys_login_logs')
    op.drop_index('ix_auditlog_module_action', table_name='sys_audit_logs')
    op.drop_table('sys_audit_logs')
    # ### end Alembic commands ###
