"""add refund_records order_reviews tables and product refundable field

Revision ID: 375d749c574a
Revises: 254143369cb9
Create Date: 2026-04-13 12:13:25.815766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '375d749c574a'
down_revision: Union[str, None] = '254143369cb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_reviews',
    sa.Column('id', sa.UUID(), nullable=False, comment='主键 (UUID v7)'),
    sa.Column('order_id', sa.UUID(), nullable=False, comment='关联订单 ID'),
    sa.Column('order_item_id', sa.UUID(), nullable=False, comment='关联订单明细 ID'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='评价用户 ID'),
    sa.Column('product_id', sa.UUID(), nullable=False, comment='商品 ID'),
    sa.Column('rating', sa.Integer(), nullable=False, comment='评分 1-5 星'),
    sa.Column('content', sa.Text(), nullable=False, comment='评价内容'),
    sa.Column('images', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='评价图片 URL 列表'),
    sa.Column('is_anonymous', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='是否匿名'),
    sa.Column('reply_content', sa.Text(), nullable=True, comment='商家回复内容'),
    sa.Column('replied_at', sa.String(length=30), nullable=True, comment='回复时间'),
    sa.Column('is_visible', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='是否展示'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间 (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间 (UTC)'),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='是否软删除'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='删除时间 (UTC)'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_order_reviews_order_id_orders')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_order_reviews_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_reviews'))
    )
    op.create_index(op.f('ix_order_reviews_order_reviews_order_id'), 'order_reviews', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_reviews_order_reviews_order_item_id'), 'order_reviews', ['order_item_id'], unique=False)
    op.create_index(op.f('ix_order_reviews_order_reviews_product_id'), 'order_reviews', ['product_id'], unique=False)
    op.create_index(op.f('ix_order_reviews_order_reviews_user_id'), 'order_reviews', ['user_id'], unique=False)
    op.create_table('refund_records',
    sa.Column('id', sa.UUID(), nullable=False, comment='主键 (UUID v7)'),
    sa.Column('refund_no', sa.String(length=32), nullable=False, comment='退款单号'),
    sa.Column('order_id', sa.UUID(), nullable=False, comment='关联订单 ID'),
    sa.Column('order_no', sa.String(length=32), nullable=False, comment='订单编号'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='买家 ID'),
    sa.Column('refund_type', sa.String(length=20), nullable=False, comment='退款类型: refund_only/return_refund'),
    sa.Column('refund_amount', sa.Numeric(precision=15, scale=2), nullable=False, comment='退款金额'),
    sa.Column('reason', sa.String(length=200), nullable=False, comment='退款原因'),
    sa.Column('description', sa.Text(), nullable=True, comment='详细说明'),
    sa.Column('images', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='凭证图片 URL 列表'),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'pending'"), nullable=False, comment='退款状态: pending/approved/returning/refunded/rejected'),
    sa.Column('admin_remark', sa.String(length=200), nullable=True, comment='管理员审核备注'),
    sa.Column('return_tracking_no', sa.String(length=50), nullable=True, comment='退货运单号'),
    sa.Column('return_company', sa.String(length=50), nullable=True, comment='退货快递公司'),
    sa.Column('approved_at', sa.String(length=30), nullable=True, comment='审核通过时间'),
    sa.Column('refunded_at', sa.String(length=30), nullable=True, comment='退款完成时间'),
    sa.Column('rejected_at', sa.String(length=30), nullable=True, comment='驳回时间'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间 (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间 (UTC)'),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='是否软删除'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='删除时间 (UTC)'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_refund_records_order_id_orders')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refund_records_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refund_records')),
    sa.UniqueConstraint('refund_no', name=op.f('uq_refund_records_refund_no'))
    )
    op.create_index(op.f('ix_refund_records_refund_records_order_id'), 'refund_records', ['order_id'], unique=False)
    op.create_index(op.f('ix_refund_records_refund_records_user_id'), 'refund_records', ['user_id'], unique=False)
    op.add_column('products', sa.Column('refundable', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='是否允许退款退货'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'refundable')
    op.drop_index(op.f('ix_refund_records_refund_records_user_id'), table_name='refund_records')
    op.drop_index(op.f('ix_refund_records_refund_records_order_id'), table_name='refund_records')
    op.drop_table('refund_records')
    op.drop_index(op.f('ix_order_reviews_order_reviews_user_id'), table_name='order_reviews')
    op.drop_index(op.f('ix_order_reviews_order_reviews_product_id'), table_name='order_reviews')
    op.drop_index(op.f('ix_order_reviews_order_reviews_order_item_id'), table_name='order_reviews')
    op.drop_index(op.f('ix_order_reviews_order_reviews_order_id'), table_name='order_reviews')
    op.drop_table('order_reviews')
    # ### end Alembic commands ###
