"""add payment_records table

Revision ID: 06e8fe8a453a
Revises: 36ab5d69d527
Create Date: 2026-04-13 10:23:17.661113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06e8fe8a453a'
down_revision: Union[str, None] = '36ab5d69d527'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_records',
    sa.Column('id', sa.UUID(), nullable=False, comment='主键 (UUID v7)'),
    sa.Column('payment_no', sa.String(length=32), nullable=False, comment='支付流水号'),
    sa.Column('order_id', sa.UUID(), nullable=False, comment='关联订单 ID'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='支付用户 ID'),
    sa.Column('payment_method', sa.String(length=20), nullable=False, comment='支付方式: wechat / balance'),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False, comment='支付金额'),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'pending'"), nullable=False, comment='支付状态: pending/paid/closed/refunding/refunded'),
    sa.Column('wechat_prepay_id', sa.String(length=64), nullable=True, comment='微信预支付 prepay_id'),
    sa.Column('wechat_transaction_id', sa.String(length=64), nullable=True, comment='微信支付交易号'),
    sa.Column('paid_at', sa.String(length=30), nullable=True, comment='支付成功时间(ISO格式)'),
    sa.Column('refund_amount', sa.Numeric(precision=15, scale=2), nullable=True, comment='退款金额'),
    sa.Column('refunded_at', sa.String(length=30), nullable=True, comment='退款时间(ISO格式)'),
    sa.Column('remark', sa.Text(), nullable=True, comment='备注/失败原因'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间 (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间 (UTC)'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment_records')),
    sa.UniqueConstraint('payment_no', name=op.f('uq_payment_records_payment_no'))
    )
    op.create_index(op.f('ix_payment_records_payment_records_order_id'), 'payment_records', ['order_id'], unique=False)
    op.create_index(op.f('ix_payment_records_payment_records_user_id'), 'payment_records', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_records_payment_records_user_id'), table_name='payment_records')
    op.drop_index(op.f('ix_payment_records_payment_records_order_id'), table_name='payment_records')
    op.drop_table('payment_records')
    # ### end Alembic commands ###
