"""feat/rbac: 建立双轨制B端管理员账权5表体系并解除C端上帝开关

Revision ID: 2b82e56e8e94
Revises: 4bcaf7442d95
Create Date: 2026-04-11 23:44:17.608218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b82e56e8e94'
down_revision: Union[str, None] = '4bcaf7442d95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sys_admins',
    sa.Column('id', sa.UUID(), nullable=False, comment='主键 (UUID v7)'),
    sa.Column('username', sa.String(length=50), nullable=False, comment='管理后台登录名'),
    sa.Column('hashed_password', sa.String(length=255), nullable=False, comment='Argon2 密码哈希'),
    sa.Column('real_name', sa.String(length=50), nullable=True, comment='内部真名/花名'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否激活'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间 (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间 (UTC)'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sys_admins'))
    )
    op.create_index(op.f('ix_sys_admins_sys_admins_username'), 'sys_admins', ['username'], unique=True)
    op.create_table('sys_permissions',
    sa.Column('id', sa.UUID(), nullable=False, comment='主键 (UUID v7)'),
    sa.Column('code', sa.String(length=100), nullable=False, comment='权限标识串 (如: order:refund)'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='显示名称 (如: 订单退款)'),
    sa.Column('type', sa.String(length=20), nullable=False, comment='类型: menu|button|api'),
    sa.Column('parent_id', sa.String(length=36), nullable=True, comment='父节点ID(用于构建菜单树)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间 (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间 (UTC)'),
    sa.CheckConstraint("type IN ('menu', 'button', 'api')", name=op.f('ck_sys_permissions_ck_sys_permission_type_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sys_permissions'))
    )
    op.create_index(op.f('ix_sys_permissions_sys_permissions_code'), 'sys_permissions', ['code'], unique=True)
    op.create_table('sys_roles',
    sa.Column('id', sa.UUID(), nullable=False, comment='主键 (UUID v7)'),
    sa.Column('code', sa.String(length=50), nullable=False, comment='角色编码 (如: FINANCE_MANAGER)'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='显示名称 (如: 财务部经理)'),
    sa.Column('description', sa.String(length=255), nullable=True, comment='描述'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间 (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间 (UTC)'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sys_roles'))
    )
    op.create_index(op.f('ix_sys_roles_sys_roles_code'), 'sys_roles', ['code'], unique=True)
    op.create_table('sys_admin_role',
    sa.Column('admin_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['sys_admins.id'], name=op.f('fk_sys_admin_role_admin_id_sys_admins'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['sys_roles.id'], name=op.f('fk_sys_admin_role_role_id_sys_roles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('admin_id', 'role_id', name=op.f('pk_sys_admin_role'))
    )
    op.create_table('sys_role_permission',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['sys_permissions.id'], name=op.f('fk_sys_role_permission_permission_id_sys_permissions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['sys_roles.id'], name=op.f('fk_sys_role_permission_role_id_sys_roles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id', name=op.f('pk_sys_role_permission'))
    )
    op.drop_column('users', 'is_superuser')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_superuser', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False, comment='是否超级管理员'))
    op.drop_table('sys_role_permission')
    op.drop_table('sys_admin_role')
    op.drop_index(op.f('ix_sys_roles_sys_roles_code'), table_name='sys_roles')
    op.drop_table('sys_roles')
    op.drop_index(op.f('ix_sys_permissions_sys_permissions_code'), table_name='sys_permissions')
    op.drop_table('sys_permissions')
    op.drop_index(op.f('ix_sys_admins_sys_admins_username'), table_name='sys_admins')
    op.drop_table('sys_admins')
    # ### end Alembic commands ###
