"""add_user_level_tables

Revision ID: bec27981acfa
Revises: 5b633cf25059
Create Date: 2026-04-12 11:04:31.227522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bec27981acfa'
down_revision: Union[str, None] = '5b633cf25059'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_levels',
    sa.Column('id', sa.UUID(), nullable=False, comment='主键 (UUID v7)'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='等级名称'),
    sa.Column('upgrade_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='升级规则 (JSONB AST 规则树，支持 AND/OR 嵌套)'),
    sa.Column('discount_rate', sa.Numeric(precision=15, scale=4), server_default=sa.text('1.0000'), nullable=False, comment='折扣率 (如 0.95 = 95折)'),
    sa.Column('commission_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment="分佣规则 [{'rank':1,'first':'3%','second':'2%','third':'1'}]"),
    sa.Column('reward_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment="升级奖励规则 [{'rank':2,'first':'100','second':'50','third':'10'}]"),
    sa.Column('icon_url', sa.String(length=500), nullable=True, comment='等级图标 URL'),
    sa.Column('description', sa.Text(), nullable=True, comment='等级权益说明 (富文本)'),
    sa.Column('rank_weight', sa.Integer(), nullable=False, comment='等级排序权重 (越大越高)'),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='是否启用'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间 (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间 (UTC)'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_levels')),
    sa.UniqueConstraint('rank_weight', name=op.f('uq_user_levels_rank_weight'))
    )
    op.create_table('user_level_profiles',
    sa.Column('id', sa.UUID(), nullable=False, comment='主键 (UUID v7)'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='关联用户 ID'),
    sa.Column('level_id', sa.UUID(), nullable=True, comment='当前等级 ID'),
    sa.Column('inviter_id', sa.UUID(), nullable=True, comment='推荐人用户 ID (直接上级)'),
    sa.Column('is_manual', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='是否人工锁定等级 (跳过自动升降级)'),
    sa.Column('total_consume', sa.Numeric(precision=15, scale=2), server_default=sa.text('0.00'), nullable=False, comment='历史累计消费净金额'),
    sa.Column('total_points', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='历史累计获得积分'),
    sa.Column('total_buy_number', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='历史累计订单数'),
    sa.Column('total_invite_number', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='累计邀请注册人数'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间 (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间 (UTC)'),
    sa.ForeignKeyConstraint(['inviter_id'], ['users.id'], name=op.f('fk_user_level_profiles_inviter_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['level_id'], ['user_levels.id'], name=op.f('fk_user_level_profiles_level_id_user_levels'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_level_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_level_profiles')),
    sa.UniqueConstraint('user_id', name=op.f('uq_user_level_profiles_user_id'))
    )
    op.create_table('user_level_records',
    sa.Column('id', sa.UUID(), nullable=False, comment='主键 (UUID v7)'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='用户 ID'),
    sa.Column('old_level_id', sa.UUID(), nullable=True, comment='变动前等级 ID'),
    sa.Column('new_level_id', sa.UUID(), nullable=False, comment='变动后等级 ID'),
    sa.Column('change_type', sa.String(length=20), nullable=False, comment='变动类型: UPGRADE / DOWNGRADE / MANUAL'),
    sa.Column('remark', sa.String(length=500), nullable=True, comment='变动说明'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间 (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间 (UTC)'),
    sa.ForeignKeyConstraint(['new_level_id'], ['user_levels.id'], name=op.f('fk_user_level_records_new_level_id_user_levels'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['old_level_id'], ['user_levels.id'], name=op.f('fk_user_level_records_old_level_id_user_levels'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_level_records_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_level_records'))
    )
    op.create_index(op.f('ix_user_level_records_user_level_records_user_id'), 'user_level_records', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_level_records_user_level_records_user_id'), table_name='user_level_records')
    op.drop_table('user_level_records')
    op.drop_table('user_level_profiles')
    op.drop_table('user_levels')
    # ### end Alembic commands ###
