"""init_all_tables

Revision ID: 97ab08d63a80
Revises: 
Create Date: 2026-04-13 16:56:19.075332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '97ab08d63a80'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.UUID(), nullable=False, comment='主键 (UUID v7)'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='分类名称'),
    sa.Column('parent_id', sa.UUID(), nullable=True, comment='父分类 ID'),
    sa.Column('icon_url', sa.String(length=500), nullable=True, comment='分类图标 URL'),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='排序权重（越大越前）'),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='是否启用'),
    sa.Column('level_prices', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='分类级等级折扣率 [{"level_id":"uuid","discount_rate":0.95}]'),
    sa.Column('level_commissions', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='分类级等级百分比分佣 [{"level_id":"uuid","first_rate":0.03,...}]'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间 (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间 (UTC)'),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], name=op.f('fk_categories_parent_id_categories'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories'))
    )
    op.create_table('commission_records',
    sa.Column('id', sa.UUID(), nullable=False, comment='主键 (UUID v7)'),
    sa.Column('order_id', sa.UUID(), nullable=False, comment='关联订单 ID'),
    sa.Column('order_no', sa.String(length=32), nullable=False, comment='订单编号'),
    sa.Column('buyer_id', sa.UUID(), nullable=False, comment='下单买家 ID'),
    sa.Column('beneficiary_id', sa.UUID(), nullable=False, comment='佣金受益人 ID'),
    sa.Column('commission_level', sa.String(length=10), nullable=False, comment='佣金层级: first/second/other'),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False, comment='佣金金额'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='佣金状态: frozen/settled/revoked'),
    sa.Column('frozen_at', sa.String(length=30), nullable=True, comment='冻结时间(ISO格式)'),
    sa.Column('settled_at', sa.String(length=30), nullable=True, comment='结算时间(ISO格式)'),
    sa.Column('revoked_at', sa.String(length=30), nullable=True, comment='撤销时间(ISO格式)'),
    sa.Column('revoke_reason', sa.String(length=200), nullable=True, comment='撤销原因'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间 (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间 (UTC)'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_commission_records'))
    )
    op.create_index(op.f('ix_commission_records_commission_records_beneficiary_id'), 'commission_records', ['beneficiary_id'], unique=False)
    op.create_index(op.f('ix_commission_records_commission_records_buyer_id'), 'commission_records', ['buyer_id'], unique=False)
    op.create_index(op.f('ix_commission_records_commission_records_order_id'), 'commission_records', ['order_id'], unique=False)
    op.create_table('payment_records',
    sa.Column('id', sa.UUID(), nullable=False, comment='主键 (UUID v7)'),
    sa.Column('payment_no', sa.String(length=32), nullable=False, comment='支付流水号'),
    sa.Column('order_id', sa.UUID(), nullable=False, comment='关联订单 ID'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='支付用户 ID'),
    sa.Column('payment_method', sa.String(length=20), nullable=False, comment='支付方式: wechat / balance'),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False, comment='支付金额'),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'pending'"), nullable=False, comment='支付状态: pending/paid/closed/refunding/refunded'),
    sa.Column('wechat_prepay_id', sa.String(length=64), nullable=True, comment='微信预支付 prepay_id'),
    sa.Column('wechat_transaction_id', sa.String(length=64), nullable=True, comment='微信支付交易号'),
    sa.Column('paid_at', sa.String(length=30), nullable=True, comment='支付成功时间(ISO格式)'),
    sa.Column('refund_amount', sa.Numeric(precision=15, scale=2), nullable=True, comment='退款金额'),
    sa.Column('refunded_at', sa.String(length=30), nullable=True, comment='退款时间(ISO格式)'),
    sa.Column('remark', sa.Text(), nullable=True, comment='备注/失败原因'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间 (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间 (UTC)'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment_records')),
    sa.UniqueConstraint('payment_no', name=op.f('uq_payment_records_payment_no'))
    )
    op.create_index(op.f('ix_payment_records_payment_records_order_id'), 'payment_records', ['order_id'], unique=False)
    op.create_index(op.f('ix_payment_records_payment_records_user_id'), 'payment_records', ['user_id'], unique=False)
    op.create_table('shipping_templates',
    sa.Column('id', sa.UUID(), nullable=False, comment='主键 (UUID v7)'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='模板名称'),
    sa.Column('pricing_method', sa.String(length=10), server_default=sa.text("'weight'"), nullable=False, comment='计价方式: weight(按重量) / piece(按件数)'),
    sa.Column('free_shipping_threshold', sa.Numeric(precision=10, scale=2), nullable=True, comment='满额包邮门槛（NULL=不设包邮，0=永远包邮）'),
    sa.Column('free_shipping_exclude_regions', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=True, comment='包邮排除的省份编码 ["650000","540000"]'),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='是否启用'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间 (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间 (UTC)'),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='是否软删除'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='删除时间 (UTC)'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shipping_templates'))
    )
    op.create_table('sms_logs',
    sa.Column('id', sa.UUID(), nullable=False, comment='主键 (UUID v7)'),
    sa.Column('phone_code', sa.String(length=10), nullable=False, comment='手机区号 (如 +86)'),
    sa.Column('mobile', sa.String(length=20), nullable=False, comment='手机号码'),
    sa.Column('sms_type', sa.String(length=30), nullable=False, comment='短信用途类型'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='发送状态'),
    sa.Column('provider', sa.String(length=20), nullable=False, comment='短信服务商'),
    sa.Column('template_id', sa.String(length=50), nullable=True, comment='短信模板 ID'),
    sa.Column('content', sa.Text(), nullable=True, comment='发送内容摘要'),
    sa.Column('request_id', sa.String(length=100), nullable=True, comment='云平台请求流水号'),
    sa.Column('fail_reason', sa.String(length=500), nullable=True, comment='失败原因'),
    sa.Column('ip_address', sa.String(length=50), nullable=True, comment='请求方 IP'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间 (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间 (UTC)'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sms_logs'))
    )
    op.create_index(op.f('ix_sms_logs_sms_logs_mobile'), 'sms_logs', ['mobile'], unique=False)
    op.create_index(op.f('ix_sms_logs_sms_logs_sms_type'), 'sms_logs', ['sms_type'], unique=False)
    op.create_table('sys_admins',
    sa.Column('id', sa.UUID(), nullable=False, comment='主键 (UUID v7)'),
    sa.Column('username', sa.String(length=50), nullable=False, comment='管理后台登录名'),
    sa.Column('hashed_password', sa.String(length=255), nullable=False, comment='Argon2 密码哈希'),
    sa.Column('real_name', sa.String(length=50), nullable=True, comment='内部真名/花名'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否激活'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间 (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间 (UTC)'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sys_admins'))
    )
    op.create_index(op.f('ix_sys_admins_sys_admins_username'), 'sys_admins', ['username'], unique=True)
    op.create_table('sys_audit_logs',
    sa.Column('id', sa.UUID(), nullable=False, comment='主键 (UUID v7)'),
    sa.Column('actor_type', sa.String(length=20), nullable=False, comment='身份集: user|admin'),
    sa.Column('actor_id', sa.String(length=36), nullable=True, comment='目标标识'),
    sa.Column('module', sa.String(length=50), nullable=False, comment='操作模块 (如: finance)'),
    sa.Column('action', sa.String(length=100), nullable=False, comment='核心动词 (如: refund)'),
    sa.Column('endpoint', sa.String(length=255), nullable=True, comment='网络层:API端点'),
    sa.Column('method', sa.String(length=10), nullable=True, comment='网络层:请求方法'),
    sa.Column('ip_address', sa.String(length=50), nullable=True, comment='发起者IP'),
    sa.Column('request_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='请求快照包裹'),
    sa.Column('response_status', sa.Integer(), nullable=True, comment='服务器返回响应码'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间 (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间 (UTC)'),
    sa.CheckConstraint("actor_type IN ('user', 'admin')", name=op.f('ck_sys_audit_logs_ck_auditlog_actortype_valid')),
    sa.CheckConstraint("request_payload IS NULL OR jsonb_typeof(request_payload) = 'object' OR jsonb_typeof(request_payload) = 'array'", name=op.f('ck_sys_audit_logs_ck_auditlog_payload_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sys_audit_logs'))
    )
    op.create_index('ix_auditlog_module_action', 'sys_audit_logs', ['module', 'action'], unique=False)
    op.create_table('sys_login_logs',
    sa.Column('id', sa.UUID(), nullable=False, comment='主键 (UUID v7)'),
    sa.Column('actor_type', sa.String(length=20), nullable=False, comment='身份集: user|admin'),
    sa.Column('actor_id', sa.String(length=36), nullable=True, comment='目标标识'),
    sa.Column('ip_address', sa.String(length=50), nullable=True, comment='来源IP'),
    sa.Column('user_agent', sa.String(length=255), nullable=True, comment='请求端指纹'),
    sa.Column('status', sa.Boolean(), nullable=False, comment='是否发放 Token 成功'),
    sa.Column('reason', sa.String(length=255), nullable=True, comment='判定明细(如: 密码错误, CAPTCHA拦截)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间 (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间 (UTC)'),
    sa.CheckConstraint("actor_type IN ('user', 'admin')", name=op.f('ck_sys_login_logs_ck_loginlog_actortype_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sys_login_logs'))
    )
    op.create_index('ix_loginlog_actor_status', 'sys_login_logs', ['actor_id', 'status'], unique=False)
    op.create_table('sys_permissions',
    sa.Column('id', sa.UUID(), nullable=False, comment='主键 (UUID v7)'),
    sa.Column('code', sa.String(length=100), nullable=False, comment='权限标识串 (如: order:refund)'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='显示名称 (如: 订单退款)'),
    sa.Column('type', sa.String(length=20), nullable=False, comment='类型: menu|button|api'),
    sa.Column('parent_id', sa.String(length=36), nullable=True, comment='父节点ID(用于构建菜单树)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间 (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间 (UTC)'),
    sa.CheckConstraint("type IN ('menu', 'button', 'api')", name=op.f('ck_sys_permissions_ck_sys_permission_type_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sys_permissions'))
    )
    op.create_index(op.f('ix_sys_permissions_sys_permissions_code'), 'sys_permissions', ['code'], unique=True)
    op.create_table('sys_roles',
    sa.Column('id', sa.UUID(), nullable=False, comment='主键 (UUID v7)'),
    sa.Column('code', sa.String(length=50), nullable=False, comment='角色编码 (如: FINANCE_MANAGER)'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='显示名称 (如: 财务部经理)'),
    sa.Column('description', sa.String(length=255), nullable=True, comment='描述'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间 (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间 (UTC)'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sys_roles'))
    )
    op.create_index(op.f('ix_sys_roles_sys_roles_code'), 'sys_roles', ['code'], unique=True)
    op.create_table('user_levels',
    sa.Column('id', sa.UUID(), nullable=False, comment='主键 (UUID v7)'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='等级名称'),
    sa.Column('upgrade_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='升级规则 (JSONB AST 规则树，支持 AND/OR 嵌套)'),
    sa.Column('discount_rate', sa.Numeric(precision=15, scale=4), server_default=sa.text('1.0000'), nullable=False, comment='折扣率 (如 0.95 = 95折)'),
    sa.Column('commission_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment="分佣规则 [{'rank':1,'first':'3%','second':'2%','other':'1'}]"),
    sa.Column('reward_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment="升级奖励规则 [{'rank':2,'first':'100','second':'50','other':'10'}]"),
    sa.Column('icon_url', sa.String(length=500), nullable=True, comment='等级图标 URL'),
    sa.Column('description', sa.Text(), nullable=True, comment='等级权益说明 (富文本)'),
    sa.Column('rank_weight', sa.Integer(), nullable=False, comment='等级排序权重 (越大越高)'),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='是否启用'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间 (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间 (UTC)'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_levels')),
    sa.UniqueConstraint('rank_weight', name=op.f('uq_user_levels_rank_weight'))
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False, comment='主键 (UUID v7)'),
    sa.Column('phone_code', sa.String(length=10), nullable=False, comment='手机区号 (如 +86)'),
    sa.Column('mobile', sa.String(length=20), nullable=False, comment='手机号 (仅号码部分)'),
    sa.Column('email', sa.String(length=255), nullable=True, comment='用户邮箱'),
    sa.Column('username', sa.String(length=50), nullable=True, comment='用户名'),
    sa.Column('hashed_password', sa.String(length=255), nullable=True, comment='密码哈希值 (短信/小程序用户可为空)'),
    sa.Column('nickname', sa.String(length=50), nullable=True, comment='用户昵称 (显示用)'),
    sa.Column('avatar', sa.String(length=255), nullable=True, comment='头像URL'),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='是否激活'),
    sa.Column('is_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='是否已实名认证'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间 (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间 (UTC)'),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='是否软删除'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='删除时间 (UTC)'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    sa.UniqueConstraint('phone_code', 'mobile', name='uq_user_phone_mobile'),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_table('addresses',
    sa.Column('id', sa.UUID(), nullable=False, comment='主键 (UUID v7)'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='归属用户'),
    sa.Column('label', sa.String(length=20), nullable=True, comment='地址标签（家/公司/自定义）'),
    sa.Column('receiver_name', sa.String(length=50), nullable=False, comment='收件人姓名'),
    sa.Column('phone_code', sa.String(length=10), server_default='+86', nullable=False, comment='手机区号（+86/+852/+853 等）'),
    sa.Column('mobile', sa.String(length=20), nullable=False, comment='手机号'),
    sa.Column('country_code', sa.String(length=10), server_default='CN', nullable=False, comment='国家编码（默认 CN）'),
    sa.Column('province', sa.String(length=50), nullable=False, comment='省名称'),
    sa.Column('province_code', sa.String(length=10), nullable=False, comment='省行政编码（如 440000）'),
    sa.Column('city', sa.String(length=50), nullable=False, comment='市名称'),
    sa.Column('city_code', sa.String(length=10), nullable=False, comment='市行政编码（如 440100）'),
    sa.Column('district', sa.String(length=50), nullable=False, comment='区/县名称'),
    sa.Column('district_code', sa.String(length=10), nullable=False, comment='区行政编码（如 440106）'),
    sa.Column('street_address', sa.String(length=200), nullable=False, comment='详细街道+门牌号'),
    sa.Column('postal_code', sa.String(length=20), nullable=True, comment='邮政编码（小程序 picker 有时返回为空）'),
    sa.Column('is_default', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='是否为默认地址（互斥由 Service 层保证唯一性）'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间 (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间 (UTC)'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_addresses_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_addresses'))
    )
    op.create_index('ix_addresses_user_id', 'addresses', ['user_id'], unique=False)
    op.create_table('media_assets',
    sa.Column('id', sa.UUID(), nullable=False, comment='主键 (UUID v7)'),
    sa.Column('admin_id', sa.UUID(), nullable=True, comment='上传的管理员ID'),
    sa.Column('file_key', sa.String(length=500), nullable=False, comment='核心源路径 (如 products/123.jpg)'),
    sa.Column('file_name', sa.String(length=255), nullable=False, comment='源文件名 (包含后缀)'),
    sa.Column('file_size', sa.Integer(), nullable=False, comment='文件字节大小'),
    sa.Column('mime_type', sa.String(length=100), nullable=False, comment='MIME 类型'),
    sa.Column('provider', sa.String(length=20), nullable=False, comment='存储提供商标识 (local/oss/s3)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间 (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间 (UTC)'),
    sa.ForeignKeyConstraint(['admin_id'], ['sys_admins.id'], name=op.f('fk_media_assets_admin_id_sys_admins'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_media_assets'))
    )
    op.create_index(op.f('ix_media_assets_media_assets_file_key'), 'media_assets', ['file_key'], unique=True)
    op.create_table('orders',
    sa.Column('id', sa.UUID(), nullable=False, comment='主键 (UUID v7)'),
    sa.Column('order_no', sa.String(length=32), nullable=False, comment='订单编号'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='买家 ID'),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'pending_payment'"), nullable=False, comment='订单状态'),
    sa.Column('address_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='收货地址快照'),
    sa.Column('items_amount', sa.Numeric(precision=15, scale=2), nullable=False, comment='商品总价'),
    sa.Column('freight_amount', sa.Numeric(precision=15, scale=2), server_default=sa.text('0.00'), nullable=False, comment='运费'),
    sa.Column('total_amount', sa.Numeric(precision=15, scale=2), nullable=False, comment='应付金额'),
    sa.Column('commission_total', sa.Numeric(precision=15, scale=2), server_default=sa.text('0.00'), nullable=False, comment='该订单产生的佣金总额'),
    sa.Column('payment_method', sa.String(length=20), nullable=True, comment='支付方式: wechat / balance'),
    sa.Column('paid_at', sa.String(length=30), nullable=True, comment='支付成功时间(ISO格式)'),
    sa.Column('shipping_company', sa.String(length=50), nullable=True, comment='快递公司'),
    sa.Column('tracking_number', sa.String(length=50), nullable=True, comment='运单号'),
    sa.Column('shipped_at', sa.String(length=30), nullable=True, comment='发货时间'),
    sa.Column('completed_at', sa.String(length=30), nullable=True, comment='确认收货时间'),
    sa.Column('cancelled_at', sa.String(length=30), nullable=True, comment='取消时间'),
    sa.Column('cancel_reason', sa.String(length=200), nullable=True, comment='取消原因'),
    sa.Column('cancelled_by', sa.UUID(), nullable=True, comment='取消操作人 ID'),
    sa.Column('remark', sa.Text(), nullable=True, comment='买家留言'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间 (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间 (UTC)'),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='是否软删除'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='删除时间 (UTC)'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_orders_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders')),
    sa.UniqueConstraint('order_no', name=op.f('uq_orders_order_no'))
    )
    op.create_index(op.f('ix_orders_orders_user_id'), 'orders', ['user_id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.UUID(), nullable=False, comment='主键 (UUID v7)'),
    sa.Column('name', sa.String(length=200), nullable=False, comment='商品标题'),
    sa.Column('subtitle', sa.String(length=500), nullable=True, comment='副标题/卖点'),
    sa.Column('product_type', sa.String(length=20), nullable=False, comment='商品类型: virtual / physical'),
    sa.Column('main_image', sa.String(length=500), nullable=False, comment='商品主图 URL'),
    sa.Column('images', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=True, comment='轮播图 URL 数组'),
    sa.Column('description', sa.Text(), nullable=True, comment='商品详情（富文本）'),
    sa.Column('market_price', sa.Numeric(precision=15, scale=2), nullable=False, comment='市场价（划线价）'),
    sa.Column('base_price', sa.Numeric(precision=15, scale=2), nullable=False, comment='本店售价'),
    sa.Column('cost_price', sa.Numeric(precision=15, scale=2), nullable=True, comment='成本价（无 SKU 时使用）'),
    sa.Column('stock', sa.Integer(), nullable=True, comment='库存（无 SKU 时使用）'),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'draft'"), nullable=False, comment='上架状态: draft / on_sale / off_sale'),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='排序权重'),
    sa.Column('sales_count', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='累计销量'),
    sa.Column('shipping_template_id', sa.UUID(), nullable=True, comment='运费模板 ID（NULL=包邮/虚拟商品）'),
    sa.Column('refundable', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='是否允许退款退货'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间 (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间 (UTC)'),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='是否软删除'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='删除时间 (UTC)'),
    sa.ForeignKeyConstraint(['shipping_template_id'], ['shipping_templates.id'], name=op.f('fk_products_shipping_template_id_shipping_templates'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products'))
    )
    op.create_table('shipping_template_regions',
    sa.Column('id', sa.UUID(), nullable=False, comment='主键 (UUID v7)'),
    sa.Column('template_id', sa.UUID(), nullable=False, comment='所属运费模板 ID'),
    sa.Column('region_name', sa.String(length=50), nullable=False, comment='地区名称（如 江浙沪皖）'),
    sa.Column('province_codes', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False, comment='省份编码数组 ["310000","320000"]，空数组=其余地区'),
    sa.Column('first_unit', sa.Numeric(precision=10, scale=2), nullable=False, comment='首重(克)/首件(件)'),
    sa.Column('first_unit_price', sa.Numeric(precision=10, scale=2), nullable=False, comment='首重/首件费用'),
    sa.Column('additional_unit', sa.Numeric(precision=10, scale=2), nullable=False, comment='续重(克)/续件(件)'),
    sa.Column('additional_unit_price', sa.Numeric(precision=10, scale=2), nullable=False, comment='每续重/续件费用'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间 (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间 (UTC)'),
    sa.ForeignKeyConstraint(['template_id'], ['shipping_templates.id'], name=op.f('fk_shipping_template_regions_template_id_shipping_templates'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shipping_template_regions'))
    )
    op.create_index(op.f('ix_shipping_template_regions_shipping_template_regions_template_id'), 'shipping_template_regions', ['template_id'], unique=False)
    op.create_table('sys_admin_role',
    sa.Column('admin_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['sys_admins.id'], name=op.f('fk_sys_admin_role_admin_id_sys_admins'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['sys_roles.id'], name=op.f('fk_sys_admin_role_role_id_sys_roles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('admin_id', 'role_id', name=op.f('pk_sys_admin_role'))
    )
    op.create_table('sys_role_permission',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['sys_permissions.id'], name=op.f('fk_sys_role_permission_permission_id_sys_permissions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['sys_roles.id'], name=op.f('fk_sys_role_permission_role_id_sys_roles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id', name=op.f('pk_sys_role_permission'))
    )
    op.create_table('user_balance_logs',
    sa.Column('id', sa.UUID(), nullable=False, comment='主键 (UUID v7)'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='归属用户ID'),
    sa.Column('change_type', sa.String(length=50), nullable=False, comment='变动类型(如order_pay/commission_first)'),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False, comment='变动金额(+/-)'),
    sa.Column('before_balance', sa.Numeric(precision=15, scale=2), nullable=False, comment='变动前余额'),
    sa.Column('after_balance', sa.Numeric(precision=15, scale=2), nullable=False, comment='变动后余额'),
    sa.Column('ref_id', sa.UUID(), nullable=True, comment='关联的业务单据ID'),
    sa.Column('remark', sa.String(length=255), nullable=True, comment='变动备注/原因说明'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间 (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间 (UTC)'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_balance_logs_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_balance_logs'))
    )
    op.create_index(op.f('ix_user_balance_logs_user_balance_logs_change_type'), 'user_balance_logs', ['change_type'], unique=False)
    op.create_index(op.f('ix_user_balance_logs_user_balance_logs_ref_id'), 'user_balance_logs', ['ref_id'], unique=False)
    op.create_index(op.f('ix_user_balance_logs_user_balance_logs_user_id'), 'user_balance_logs', ['user_id'], unique=False)
    op.create_table('user_level_profiles',
    sa.Column('id', sa.UUID(), nullable=False, comment='主键 (UUID v7)'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='关联用户 ID'),
    sa.Column('level_id', sa.UUID(), nullable=True, comment='当前等级 ID'),
    sa.Column('inviter_id', sa.UUID(), nullable=True, comment='推荐人用户 ID (直接上级)'),
    sa.Column('invite_code', sa.String(length=20), nullable=True, comment='用户专属邀请码'),
    sa.Column('invited_at', sa.String(length=30), nullable=True, comment='被邀请绑定时间'),
    sa.Column('is_manual', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='是否人工锁定等级 (跳过自动升降级)'),
    sa.Column('total_consume', sa.Numeric(precision=15, scale=2), server_default=sa.text('0.00'), nullable=False, comment='历史累计消费净金额'),
    sa.Column('total_points', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='历史累计获得积分'),
    sa.Column('total_buy_number', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='历史累计订单数'),
    sa.Column('total_invite_number', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='累计邀请注册人数'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间 (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间 (UTC)'),
    sa.ForeignKeyConstraint(['inviter_id'], ['users.id'], name=op.f('fk_user_level_profiles_inviter_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['level_id'], ['user_levels.id'], name=op.f('fk_user_level_profiles_level_id_user_levels'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_level_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_level_profiles')),
    sa.UniqueConstraint('invite_code', name=op.f('uq_user_level_profiles_invite_code')),
    sa.UniqueConstraint('user_id', name=op.f('uq_user_level_profiles_user_id'))
    )
    op.create_index(op.f('ix_user_level_profiles_user_level_profiles_inviter_id'), 'user_level_profiles', ['inviter_id'], unique=False)
    op.create_table('user_level_records',
    sa.Column('id', sa.UUID(), nullable=False, comment='主键 (UUID v7)'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='用户 ID'),
    sa.Column('old_level_id', sa.UUID(), nullable=True, comment='变动前等级 ID'),
    sa.Column('new_level_id', sa.UUID(), nullable=False, comment='变动后等级 ID'),
    sa.Column('change_type', sa.String(length=20), nullable=False, comment='变动类型: UPGRADE / DOWNGRADE / MANUAL'),
    sa.Column('remark', sa.String(length=500), nullable=True, comment='变动说明'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间 (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间 (UTC)'),
    sa.ForeignKeyConstraint(['new_level_id'], ['user_levels.id'], name=op.f('fk_user_level_records_new_level_id_user_levels'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['old_level_id'], ['user_levels.id'], name=op.f('fk_user_level_records_old_level_id_user_levels'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_level_records_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_level_records'))
    )
    op.create_index(op.f('ix_user_level_records_user_level_records_user_id'), 'user_level_records', ['user_id'], unique=False)
    op.create_table('user_point_logs',
    sa.Column('id', sa.UUID(), nullable=False, comment='主键 (UUID v7)'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='归属用户ID'),
    sa.Column('change_type', sa.String(length=50), nullable=False, comment='变动类型(如sign_in/order_complete)'),
    sa.Column('points', sa.Integer(), nullable=False, comment='变动积分(+/-)'),
    sa.Column('before_points', sa.Integer(), nullable=False, comment='变动前积分'),
    sa.Column('after_points', sa.Integer(), nullable=False, comment='变动后积分'),
    sa.Column('ref_id', sa.UUID(), nullable=True, comment='关联的业务单据ID'),
    sa.Column('remark', sa.String(length=255), nullable=True, comment='变动备注/原因说明'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间 (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间 (UTC)'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_point_logs_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_point_logs'))
    )
    op.create_index(op.f('ix_user_point_logs_user_point_logs_change_type'), 'user_point_logs', ['change_type'], unique=False)
    op.create_index(op.f('ix_user_point_logs_user_point_logs_ref_id'), 'user_point_logs', ['ref_id'], unique=False)
    op.create_index(op.f('ix_user_point_logs_user_point_logs_user_id'), 'user_point_logs', ['user_id'], unique=False)
    op.create_table('user_socials',
    sa.Column('id', sa.UUID(), nullable=False, comment='主键 (UUID v7)'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='关联用户ID'),
    sa.Column('platform', sa.String(length=50), nullable=False, comment='平台标识'),
    sa.Column('openid', sa.String(length=255), nullable=False, comment='三方唯一ID(OpenID)'),
    sa.Column('unionid', sa.String(length=255), nullable=True, comment='微信UnionID'),
    sa.Column('session_key', sa.String(length=255), nullable=True, comment='微信 session_key (加密密钥)'),
    sa.Column('nickname', sa.String(length=100), nullable=True, comment='三方平台昵称'),
    sa.Column('avatar', sa.String(length=500), nullable=True, comment='三方平台头像URL'),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='三方原始数据快照'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间 (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间 (UTC)'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_socials_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_socials')),
    sa.UniqueConstraint('platform', 'openid', name='uq_social_platform_openid')
    )
    op.create_index(op.f('ix_user_socials_user_socials_openid'), 'user_socials', ['openid'], unique=False)
    op.create_index(op.f('ix_user_socials_user_socials_platform'), 'user_socials', ['platform'], unique=False)
    op.create_index(op.f('ix_user_socials_user_socials_unionid'), 'user_socials', ['unionid'], unique=False)
    op.create_index(op.f('ix_user_socials_user_socials_user_id'), 'user_socials', ['user_id'], unique=False)
    op.create_table('user_wallets',
    sa.Column('id', sa.UUID(), nullable=False, comment='主键 (UUID v7)'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='归属用户ID'),
    sa.Column('balance', sa.Numeric(precision=15, scale=2), nullable=False, comment='当前可用现金余额'),
    sa.Column('frozen_balance', sa.Numeric(precision=15, scale=2), nullable=False, comment='提现审核等冻结的余额'),
    sa.Column('points', sa.Integer(), nullable=False, comment='当前可用总积分'),
    sa.Column('version', sa.Integer(), nullable=False, comment='乐观锁版本号'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间 (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间 (UTC)'),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='是否软删除'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='删除时间 (UTC)'),
    sa.CheckConstraint('balance >= 0', name=op.f('ck_user_wallets_ck_wallet_balance_positive')),
    sa.CheckConstraint('frozen_balance >= 0', name=op.f('ck_user_wallets_ck_wallet_frozen_positive')),
    sa.CheckConstraint('points >= 0', name=op.f('ck_user_wallets_ck_wallet_points_positive')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_wallets_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_wallets')),
    sa.UniqueConstraint('user_id', name=op.f('uq_user_wallets_user_id'))
    )
    op.create_table('withdrawal_records',
    sa.Column('id', sa.UUID(), nullable=False, comment='主键 (UUID v7)'),
    sa.Column('withdrawal_no', sa.String(length=32), nullable=False, comment='提现单号'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='申请用户 ID'),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False, comment='提现金额'),
    sa.Column('fee', sa.Numeric(precision=15, scale=2), server_default=sa.text('0.00'), nullable=False, comment='手续费'),
    sa.Column('actual_amount', sa.Numeric(precision=15, scale=2), nullable=False, comment='实际到账金额'),
    sa.Column('channel', sa.String(length=30), nullable=False, comment='提现通道'),
    sa.Column('account_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='收款账号信息'),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'pending'"), nullable=False, comment='提现状态: pending/approved/completed/rejected'),
    sa.Column('admin_remark', sa.String(length=200), nullable=True, comment='管理员审核备注'),
    sa.Column('reviewed_by', sa.UUID(), nullable=True, comment='审核人 ID'),
    sa.Column('reviewed_at', sa.String(length=30), nullable=True, comment='审核时间'),
    sa.Column('completed_at', sa.String(length=30), nullable=True, comment='打款完成时间'),
    sa.Column('rejected_at', sa.String(length=30), nullable=True, comment='驳回时间'),
    sa.Column('remark', sa.String(length=200), nullable=True, comment='用户备注'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间 (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间 (UTC)'),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='是否软删除'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='删除时间 (UTC)'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_withdrawal_records_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_withdrawal_records')),
    sa.UniqueConstraint('withdrawal_no', name=op.f('uq_withdrawal_records_withdrawal_no'))
    )
    op.create_index(op.f('ix_withdrawal_records_withdrawal_records_user_id'), 'withdrawal_records', ['user_id'], unique=False)
    op.create_table('order_items',
    sa.Column('id', sa.UUID(), nullable=False, comment='主键 (UUID v7)'),
    sa.Column('order_id', sa.UUID(), nullable=False, comment='所属订单 ID'),
    sa.Column('product_id', sa.UUID(), nullable=False, comment='商品 ID'),
    sa.Column('sku_id', sa.UUID(), nullable=True, comment='SKU ID'),
    sa.Column('product_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='商品快照 { name, main_image, product_type }'),
    sa.Column('sku_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='SKU 快照 { sku_code, spec_values, image_url, weight }'),
    sa.Column('unit_price', sa.Numeric(precision=15, scale=2), nullable=False, comment='下单时单价'),
    sa.Column('quantity', sa.Integer(), nullable=False, comment='购买数量'),
    sa.Column('subtotal', sa.Numeric(precision=15, scale=2), nullable=False, comment='小计'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间 (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间 (UTC)'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_order_items_order_id_orders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_items'))
    )
    op.create_index(op.f('ix_order_items_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    op.create_table('order_reviews',
    sa.Column('id', sa.UUID(), nullable=False, comment='主键 (UUID v7)'),
    sa.Column('order_id', sa.UUID(), nullable=False, comment='关联订单 ID'),
    sa.Column('order_item_id', sa.UUID(), nullable=False, comment='关联订单明细 ID'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='评价用户 ID'),
    sa.Column('product_id', sa.UUID(), nullable=False, comment='商品 ID'),
    sa.Column('rating', sa.Integer(), nullable=False, comment='评分 1-5 星'),
    sa.Column('content', sa.Text(), nullable=False, comment='评价内容'),
    sa.Column('images', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='评价图片 URL 列表'),
    sa.Column('is_anonymous', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='是否匿名'),
    sa.Column('reply_content', sa.Text(), nullable=True, comment='商家回复内容'),
    sa.Column('replied_at', sa.String(length=30), nullable=True, comment='回复时间'),
    sa.Column('is_visible', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='是否展示'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间 (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间 (UTC)'),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='是否软删除'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='删除时间 (UTC)'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_order_reviews_order_id_orders')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_order_reviews_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_reviews'))
    )
    op.create_index(op.f('ix_order_reviews_order_reviews_order_id'), 'order_reviews', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_reviews_order_reviews_order_item_id'), 'order_reviews', ['order_item_id'], unique=False)
    op.create_index(op.f('ix_order_reviews_order_reviews_product_id'), 'order_reviews', ['product_id'], unique=False)
    op.create_index(op.f('ix_order_reviews_order_reviews_user_id'), 'order_reviews', ['user_id'], unique=False)
    op.create_table('product_categories',
    sa.Column('id', sa.UUID(), nullable=False, comment='主键 (UUID v7)'),
    sa.Column('product_id', sa.UUID(), nullable=False, comment='商品 ID'),
    sa.Column('category_id', sa.UUID(), nullable=False, comment='分类 ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间 (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间 (UTC)'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_product_categories_category_id_categories'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_categories_product_id_products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_categories')),
    sa.UniqueConstraint('product_id', 'category_id', name='uq_product_category')
    )
    op.create_table('product_level_commissions',
    sa.Column('id', sa.UUID(), nullable=False, comment='主键 (UUID v7)'),
    sa.Column('product_id', sa.UUID(), nullable=False, comment='归属商品 ID'),
    sa.Column('level_id', sa.UUID(), nullable=False, comment='推荐人等级 ID'),
    sa.Column('commission_first', sa.Numeric(precision=15, scale=2), nullable=False, comment='直推佣金固定金额'),
    sa.Column('commission_second', sa.Numeric(precision=15, scale=2), server_default=sa.text('0.00'), nullable=False, comment='间推佣金固定金额'),
    sa.Column('commission_other', sa.Numeric(precision=15, scale=2), server_default=sa.text('0.00'), nullable=False, comment='其它层级佣金固定金额'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间 (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间 (UTC)'),
    sa.ForeignKeyConstraint(['level_id'], ['user_levels.id'], name=op.f('fk_product_level_commissions_level_id_user_levels'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_level_commissions_product_id_products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_level_commissions')),
    sa.UniqueConstraint('product_id', 'level_id', name='uq_product_level_commission')
    )
    op.create_table('product_skus',
    sa.Column('id', sa.UUID(), nullable=False, comment='主键 (UUID v7)'),
    sa.Column('product_id', sa.UUID(), nullable=False, comment='归属商品 ID'),
    sa.Column('sku_code', sa.String(length=100), nullable=False, comment='SKU 唯一编码'),
    sa.Column('spec_values', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='规格组合 {"颜色":"红色","尺寸":"XL"}'),
    sa.Column('price', sa.Numeric(precision=15, scale=2), nullable=False, comment='SKU 独立售价'),
    sa.Column('cost_price', sa.Numeric(precision=15, scale=2), nullable=True, comment='成本价'),
    sa.Column('stock', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='库存数量'),
    sa.Column('image_url', sa.String(length=500), nullable=True, comment='SKU 专属图片'),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='是否启用'),
    sa.Column('weight', sa.Numeric(precision=10, scale=2), server_default=sa.text('0.00'), nullable=False, comment='重量（克），用于运费计算'),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='显示顺序'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间 (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间 (UTC)'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_skus_product_id_products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_skus')),
    sa.UniqueConstraint('sku_code', name=op.f('uq_product_skus_sku_code'))
    )
    op.create_index(op.f('ix_product_skus_product_skus_product_id'), 'product_skus', ['product_id'], unique=False)
    op.create_table('product_specs',
    sa.Column('id', sa.UUID(), nullable=False, comment='主键 (UUID v7)'),
    sa.Column('product_id', sa.UUID(), nullable=False, comment='归属商品 ID'),
    sa.Column('spec_name', sa.String(length=50), nullable=False, comment='规格名称（如颜色、尺寸）'),
    sa.Column('spec_values', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='候选值数组 ["红色","蓝色","白色"]'),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='展示顺序'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间 (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间 (UTC)'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_specs_product_id_products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_specs')),
    sa.UniqueConstraint('product_id', 'spec_name', name='uq_product_spec_name')
    )
    op.create_table('product_views',
    sa.Column('id', sa.UUID(), nullable=False, comment='主键 (UUID v7)'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='访客 ID'),
    sa.Column('product_id', sa.UUID(), nullable=False, comment='被浏览商品的 SPU ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间 (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间 (UTC)'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_views_product_id_products'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_product_views_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_views')),
    sa.UniqueConstraint('user_id', 'product_id', name='uq_product_views_user_product')
    )
    op.create_index(op.f('ix_product_views_product_views_user_id'), 'product_views', ['user_id'], unique=False)
    op.create_table('refund_records',
    sa.Column('id', sa.UUID(), nullable=False, comment='主键 (UUID v7)'),
    sa.Column('refund_no', sa.String(length=32), nullable=False, comment='退款单号'),
    sa.Column('order_id', sa.UUID(), nullable=False, comment='关联订单 ID'),
    sa.Column('order_no', sa.String(length=32), nullable=False, comment='订单编号'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='买家 ID'),
    sa.Column('refund_type', sa.String(length=20), nullable=False, comment='退款类型: refund_only/return_refund'),
    sa.Column('refund_amount', sa.Numeric(precision=15, scale=2), nullable=False, comment='退款金额'),
    sa.Column('reason', sa.String(length=200), nullable=False, comment='退款原因'),
    sa.Column('description', sa.Text(), nullable=True, comment='详细说明'),
    sa.Column('images', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='凭证图片 URL 列表'),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'pending'"), nullable=False, comment='退款状态: pending/approved/returning/refunded/rejected'),
    sa.Column('admin_remark', sa.String(length=200), nullable=True, comment='管理员审核备注'),
    sa.Column('return_tracking_no', sa.String(length=50), nullable=True, comment='退货运单号'),
    sa.Column('return_company', sa.String(length=50), nullable=True, comment='退货快递公司'),
    sa.Column('approved_at', sa.String(length=30), nullable=True, comment='审核通过时间'),
    sa.Column('refunded_at', sa.String(length=30), nullable=True, comment='退款完成时间'),
    sa.Column('rejected_at', sa.String(length=30), nullable=True, comment='驳回时间'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间 (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间 (UTC)'),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='是否软删除'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='删除时间 (UTC)'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_refund_records_order_id_orders')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refund_records_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refund_records')),
    sa.UniqueConstraint('refund_no', name=op.f('uq_refund_records_refund_no'))
    )
    op.create_index(op.f('ix_refund_records_refund_records_order_id'), 'refund_records', ['order_id'], unique=False)
    op.create_index(op.f('ix_refund_records_refund_records_user_id'), 'refund_records', ['user_id'], unique=False)
    op.create_table('cart_items',
    sa.Column('id', sa.UUID(), nullable=False, comment='主键 (UUID v7)'),
    sa.Column('user_id', sa.UUID(), nullable=True, comment='实名归属（与 anonymous_id 必有一填）'),
    sa.Column('anonymous_id', sa.String(length=128), nullable=True, comment='游客设备的唯一特征指纹'),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('sku_id', sa.UUID(), nullable=True, comment='如果商品带变体必选'),
    sa.Column('quantity', sa.Integer(), nullable=False, comment='件数'),
    sa.Column('selected', sa.Boolean(), nullable=False, comment='UI 选定结算状态'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间 (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间 (UTC)'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_cart_items_product_id_products'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sku_id'], ['product_skus.id'], name=op.f('fk_cart_items_sku_id_product_skus'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_cart_items_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cart_items'))
    )
    op.create_index('ix_cart_items_user_or_anon', 'cart_items', ['user_id', 'anonymous_id'], unique=False)
    op.create_table('product_level_prices',
    sa.Column('id', sa.UUID(), nullable=False, comment='主键 (UUID v7)'),
    sa.Column('product_id', sa.UUID(), nullable=False, comment='归属商品 ID'),
    sa.Column('sku_id', sa.UUID(), nullable=True, comment='指定 SKU（null = 商品级）'),
    sa.Column('level_id', sa.UUID(), nullable=False, comment='会员等级 ID'),
    sa.Column('price', sa.Numeric(precision=15, scale=2), nullable=False, comment='该等级的固定售价'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间 (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间 (UTC)'),
    sa.ForeignKeyConstraint(['level_id'], ['user_levels.id'], name=op.f('fk_product_level_prices_level_id_user_levels'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_level_prices_product_id_products'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sku_id'], ['product_skus.id'], name=op.f('fk_product_level_prices_sku_id_product_skus'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_level_prices')),
    sa.UniqueConstraint('product_id', 'sku_id', 'level_id', name='uq_product_sku_level_price')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_level_prices')
    op.drop_index('ix_cart_items_user_or_anon', table_name='cart_items')
    op.drop_table('cart_items')
    op.drop_index(op.f('ix_refund_records_refund_records_user_id'), table_name='refund_records')
    op.drop_index(op.f('ix_refund_records_refund_records_order_id'), table_name='refund_records')
    op.drop_table('refund_records')
    op.drop_index(op.f('ix_product_views_product_views_user_id'), table_name='product_views')
    op.drop_table('product_views')
    op.drop_table('product_specs')
    op.drop_index(op.f('ix_product_skus_product_skus_product_id'), table_name='product_skus')
    op.drop_table('product_skus')
    op.drop_table('product_level_commissions')
    op.drop_table('product_categories')
    op.drop_index(op.f('ix_order_reviews_order_reviews_user_id'), table_name='order_reviews')
    op.drop_index(op.f('ix_order_reviews_order_reviews_product_id'), table_name='order_reviews')
    op.drop_index(op.f('ix_order_reviews_order_reviews_order_item_id'), table_name='order_reviews')
    op.drop_index(op.f('ix_order_reviews_order_reviews_order_id'), table_name='order_reviews')
    op.drop_table('order_reviews')
    op.drop_index(op.f('ix_order_items_order_items_order_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_withdrawal_records_withdrawal_records_user_id'), table_name='withdrawal_records')
    op.drop_table('withdrawal_records')
    op.drop_table('user_wallets')
    op.drop_index(op.f('ix_user_socials_user_socials_user_id'), table_name='user_socials')
    op.drop_index(op.f('ix_user_socials_user_socials_unionid'), table_name='user_socials')
    op.drop_index(op.f('ix_user_socials_user_socials_platform'), table_name='user_socials')
    op.drop_index(op.f('ix_user_socials_user_socials_openid'), table_name='user_socials')
    op.drop_table('user_socials')
    op.drop_index(op.f('ix_user_point_logs_user_point_logs_user_id'), table_name='user_point_logs')
    op.drop_index(op.f('ix_user_point_logs_user_point_logs_ref_id'), table_name='user_point_logs')
    op.drop_index(op.f('ix_user_point_logs_user_point_logs_change_type'), table_name='user_point_logs')
    op.drop_table('user_point_logs')
    op.drop_index(op.f('ix_user_level_records_user_level_records_user_id'), table_name='user_level_records')
    op.drop_table('user_level_records')
    op.drop_index(op.f('ix_user_level_profiles_user_level_profiles_inviter_id'), table_name='user_level_profiles')
    op.drop_table('user_level_profiles')
    op.drop_index(op.f('ix_user_balance_logs_user_balance_logs_user_id'), table_name='user_balance_logs')
    op.drop_index(op.f('ix_user_balance_logs_user_balance_logs_ref_id'), table_name='user_balance_logs')
    op.drop_index(op.f('ix_user_balance_logs_user_balance_logs_change_type'), table_name='user_balance_logs')
    op.drop_table('user_balance_logs')
    op.drop_table('sys_role_permission')
    op.drop_table('sys_admin_role')
    op.drop_index(op.f('ix_shipping_template_regions_shipping_template_regions_template_id'), table_name='shipping_template_regions')
    op.drop_table('shipping_template_regions')
    op.drop_table('products')
    op.drop_index(op.f('ix_orders_orders_user_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_media_assets_media_assets_file_key'), table_name='media_assets')
    op.drop_table('media_assets')
    op.drop_index('ix_addresses_user_id', table_name='addresses')
    op.drop_table('addresses')
    op.drop_table('users')
    op.drop_table('user_levels')
    op.drop_index(op.f('ix_sys_roles_sys_roles_code'), table_name='sys_roles')
    op.drop_table('sys_roles')
    op.drop_index(op.f('ix_sys_permissions_sys_permissions_code'), table_name='sys_permissions')
    op.drop_table('sys_permissions')
    op.drop_index('ix_loginlog_actor_status', table_name='sys_login_logs')
    op.drop_table('sys_login_logs')
    op.drop_index('ix_auditlog_module_action', table_name='sys_audit_logs')
    op.drop_table('sys_audit_logs')
    op.drop_index(op.f('ix_sys_admins_sys_admins_username'), table_name='sys_admins')
    op.drop_table('sys_admins')
    op.drop_index(op.f('ix_sms_logs_sms_logs_sms_type'), table_name='sms_logs')
    op.drop_index(op.f('ix_sms_logs_sms_logs_mobile'), table_name='sms_logs')
    op.drop_table('sms_logs')
    op.drop_table('shipping_templates')
    op.drop_index(op.f('ix_payment_records_payment_records_user_id'), table_name='payment_records')
    op.drop_index(op.f('ix_payment_records_payment_records_order_id'), table_name='payment_records')
    op.drop_table('payment_records')
    op.drop_index(op.f('ix_commission_records_commission_records_order_id'), table_name='commission_records')
    op.drop_index(op.f('ix_commission_records_commission_records_buyer_id'), table_name='commission_records')
    op.drop_index(op.f('ix_commission_records_commission_records_beneficiary_id'), table_name='commission_records')
    op.drop_table('commission_records')
    op.drop_table('categories')
    # ### end Alembic commands ###
