"""feat: user addresses domain

Revision ID: 01e8cf3d423c
Revises: 000b8363728f
Create Date: 2026-04-12 22:49:10.996603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01e8cf3d423c'
down_revision: Union[str, None] = '000b8363728f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addresses',
    sa.Column('id', sa.UUID(), nullable=False, comment='主键 (UUID v7)'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='归属用户'),
    sa.Column('label', sa.String(length=20), nullable=True, comment='地址标签（家/公司/自定义）'),
    sa.Column('receiver_name', sa.String(length=50), nullable=False, comment='收件人姓名'),
    sa.Column('phone_code', sa.String(length=10), server_default='+86', nullable=False, comment='手机区号（+86/+852/+853 等）'),
    sa.Column('mobile', sa.String(length=20), nullable=False, comment='手机号'),
    sa.Column('country_code', sa.String(length=10), server_default='CN', nullable=False, comment='国家编码（默认 CN）'),
    sa.Column('province', sa.String(length=50), nullable=False, comment='省名称'),
    sa.Column('province_code', sa.String(length=10), nullable=False, comment='省行政编码（如 440000）'),
    sa.Column('city', sa.String(length=50), nullable=False, comment='市名称'),
    sa.Column('city_code', sa.String(length=10), nullable=False, comment='市行政编码（如 440100）'),
    sa.Column('district', sa.String(length=50), nullable=False, comment='区/县名称'),
    sa.Column('district_code', sa.String(length=10), nullable=False, comment='区行政编码（如 440106）'),
    sa.Column('street_address', sa.String(length=200), nullable=False, comment='详细街道+门牌号'),
    sa.Column('postal_code', sa.String(length=20), nullable=True, comment='邮政编码（小程序 picker 有时返回为空）'),
    sa.Column('is_default', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='是否为默认地址（互斥由 Service 层保证唯一性）'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间 (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间 (UTC)'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_addresses_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_addresses'))
    )
    op.create_index('ix_addresses_user_id', 'addresses', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_addresses_user_id', table_name='addresses')
    op.drop_table('addresses')
    # ### end Alembic commands ###
