"""add orders order_items commission_records tables

Revision ID: 254143369cb9
Revises: 06e8fe8a453a
Create Date: 2026-04-13 11:30:16.786636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '254143369cb9'
down_revision: Union[str, None] = '06e8fe8a453a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commission_records',
    sa.Column('id', sa.UUID(), nullable=False, comment='主键 (UUID v7)'),
    sa.Column('order_id', sa.UUID(), nullable=False, comment='关联订单 ID'),
    sa.Column('order_no', sa.String(length=32), nullable=False, comment='订单编号'),
    sa.Column('buyer_id', sa.UUID(), nullable=False, comment='下单买家 ID'),
    sa.Column('beneficiary_id', sa.UUID(), nullable=False, comment='佣金受益人 ID'),
    sa.Column('commission_level', sa.String(length=10), nullable=False, comment='佣金层级: first/second/other'),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False, comment='佣金金额'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='佣金状态: frozen/settled/revoked'),
    sa.Column('frozen_at', sa.String(length=30), nullable=True, comment='冻结时间(ISO格式)'),
    sa.Column('settled_at', sa.String(length=30), nullable=True, comment='结算时间(ISO格式)'),
    sa.Column('revoked_at', sa.String(length=30), nullable=True, comment='撤销时间(ISO格式)'),
    sa.Column('revoke_reason', sa.String(length=200), nullable=True, comment='撤销原因'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间 (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间 (UTC)'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_commission_records'))
    )
    op.create_index(op.f('ix_commission_records_commission_records_beneficiary_id'), 'commission_records', ['beneficiary_id'], unique=False)
    op.create_index(op.f('ix_commission_records_commission_records_buyer_id'), 'commission_records', ['buyer_id'], unique=False)
    op.create_index(op.f('ix_commission_records_commission_records_order_id'), 'commission_records', ['order_id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.UUID(), nullable=False, comment='主键 (UUID v7)'),
    sa.Column('order_no', sa.String(length=32), nullable=False, comment='订单编号'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='买家 ID'),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'pending_payment'"), nullable=False, comment='订单状态'),
    sa.Column('address_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='收货地址快照'),
    sa.Column('items_amount', sa.Numeric(precision=15, scale=2), nullable=False, comment='商品总价'),
    sa.Column('freight_amount', sa.Numeric(precision=15, scale=2), server_default=sa.text('0.00'), nullable=False, comment='运费'),
    sa.Column('total_amount', sa.Numeric(precision=15, scale=2), nullable=False, comment='应付金额'),
    sa.Column('commission_total', sa.Numeric(precision=15, scale=2), server_default=sa.text('0.00'), nullable=False, comment='该订单产生的佣金总额'),
    sa.Column('payment_method', sa.String(length=20), nullable=True, comment='支付方式: wechat / balance'),
    sa.Column('paid_at', sa.String(length=30), nullable=True, comment='支付成功时间(ISO格式)'),
    sa.Column('shipping_company', sa.String(length=50), nullable=True, comment='快递公司'),
    sa.Column('tracking_number', sa.String(length=50), nullable=True, comment='运单号'),
    sa.Column('shipped_at', sa.String(length=30), nullable=True, comment='发货时间'),
    sa.Column('completed_at', sa.String(length=30), nullable=True, comment='确认收货时间'),
    sa.Column('cancelled_at', sa.String(length=30), nullable=True, comment='取消时间'),
    sa.Column('cancel_reason', sa.String(length=200), nullable=True, comment='取消原因'),
    sa.Column('cancelled_by', sa.UUID(), nullable=True, comment='取消操作人 ID'),
    sa.Column('remark', sa.Text(), nullable=True, comment='买家留言'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间 (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间 (UTC)'),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='是否软删除'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='删除时间 (UTC)'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_orders_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders')),
    sa.UniqueConstraint('order_no', name=op.f('uq_orders_order_no'))
    )
    op.create_index(op.f('ix_orders_orders_user_id'), 'orders', ['user_id'], unique=False)
    op.create_table('order_items',
    sa.Column('id', sa.UUID(), nullable=False, comment='主键 (UUID v7)'),
    sa.Column('order_id', sa.UUID(), nullable=False, comment='所属订单 ID'),
    sa.Column('product_id', sa.UUID(), nullable=False, comment='商品 ID'),
    sa.Column('sku_id', sa.UUID(), nullable=True, comment='SKU ID'),
    sa.Column('product_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='商品快照 { name, main_image, product_type }'),
    sa.Column('sku_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='SKU 快照 { sku_code, spec_values, image_url, weight }'),
    sa.Column('unit_price', sa.Numeric(precision=15, scale=2), nullable=False, comment='下单时单价'),
    sa.Column('quantity', sa.Integer(), nullable=False, comment='购买数量'),
    sa.Column('subtotal', sa.Numeric(precision=15, scale=2), nullable=False, comment='小计'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间 (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间 (UTC)'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_order_items_order_id_orders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_items'))
    )
    op.create_index(op.f('ix_order_items_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_items_order_items_order_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_orders_orders_user_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_commission_records_commission_records_order_id'), table_name='commission_records')
    op.drop_index(op.f('ix_commission_records_commission_records_buyer_id'), table_name='commission_records')
    op.drop_index(op.f('ix_commission_records_commission_records_beneficiary_id'), table_name='commission_records')
    op.drop_table('commission_records')
    # ### end Alembic commands ###
