"""feat: media asset tracking

Revision ID: a0a1a71326eb
Revises: 3d49919fb143
Create Date: 2026-04-12 21:44:28.739134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0a1a71326eb'
down_revision: Union[str, None] = '3d49919fb143'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media_assets',
    sa.Column('id', sa.UUID(), nullable=False, comment='主键 (UUID v7)'),
    sa.Column('admin_id', sa.UUID(), nullable=True, comment='上传的管理员ID'),
    sa.Column('file_key', sa.String(length=500), nullable=False, comment='核心源路径 (如 products/123.jpg)'),
    sa.Column('file_name', sa.String(length=255), nullable=False, comment='源文件名 (包含后缀)'),
    sa.Column('file_size', sa.Integer(), nullable=False, comment='文件字节大小'),
    sa.Column('mime_type', sa.String(length=100), nullable=False, comment='MIME 类型'),
    sa.Column('provider', sa.String(length=20), nullable=False, comment='存储提供商标识 (local/oss/s3)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间 (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间 (UTC)'),
    sa.ForeignKeyConstraint(['admin_id'], ['sys_admins.id'], name=op.f('fk_media_assets_admin_id_sys_admins'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_media_assets'))
    )
    op.create_index(op.f('ix_media_assets_media_assets_file_key'), 'media_assets', ['file_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_media_assets_media_assets_file_key'), table_name='media_assets')
    op.drop_table('media_assets')
    # ### end Alembic commands ###
