"""rescue_init_sorted

Revision ID: 4bcaf7442d95
Revises: 
Create Date: 2026-04-11 21:32:43.962337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bcaf7442d95'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False, comment='主键 (UUID v7)'),
    sa.Column('phone_code', sa.String(length=10), nullable=False, comment='手机区号 (如 +86)'),
    sa.Column('mobile', sa.String(length=20), nullable=False, comment='手机号 (仅号码部分)'),
    sa.Column('email', sa.String(length=255), nullable=True, comment='用户邮箱'),
    sa.Column('username', sa.String(length=50), nullable=True, comment='用户名'),
    sa.Column('hashed_password', sa.String(length=255), nullable=False, comment='密码哈希值'),
    sa.Column('nickname', sa.String(length=50), nullable=True, comment='用户昵称 (显示用)'),
    sa.Column('avatar', sa.String(length=255), nullable=True, comment='头像URL'),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='是否激活'),
    sa.Column('is_superuser', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='是否超级管理员'),
    sa.Column('is_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='是否已实名认证'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间 (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间 (UTC)'),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='是否软删除'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='删除时间 (UTC)'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    sa.UniqueConstraint('phone_code', 'mobile', name='uq_user_phone_mobile'),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
