"""add withdrawal_records table

Revision ID: 1cb24589aa86
Revises: df16ff406d52
Create Date: 2026-04-13 16:42:04.712109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1cb24589aa86'
down_revision: Union[str, None] = 'df16ff406d52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('withdrawal_records',
    sa.Column('id', sa.UUID(), nullable=False, comment='主键 (UUID v7)'),
    sa.Column('withdrawal_no', sa.String(length=32), nullable=False, comment='提现单号'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='申请用户 ID'),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False, comment='提现金额'),
    sa.Column('fee', sa.Numeric(precision=15, scale=2), server_default=sa.text('0.00'), nullable=False, comment='手续费'),
    sa.Column('actual_amount', sa.Numeric(precision=15, scale=2), nullable=False, comment='实际到账金额'),
    sa.Column('channel', sa.String(length=30), nullable=False, comment='提现通道'),
    sa.Column('account_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='收款账号信息'),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'pending'"), nullable=False, comment='提现状态: pending/approved/completed/rejected'),
    sa.Column('admin_remark', sa.String(length=200), nullable=True, comment='管理员审核备注'),
    sa.Column('reviewed_by', sa.UUID(), nullable=True, comment='审核人 ID'),
    sa.Column('reviewed_at', sa.String(length=30), nullable=True, comment='审核时间'),
    sa.Column('completed_at', sa.String(length=30), nullable=True, comment='打款完成时间'),
    sa.Column('rejected_at', sa.String(length=30), nullable=True, comment='驳回时间'),
    sa.Column('remark', sa.String(length=200), nullable=True, comment='用户备注'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间 (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间 (UTC)'),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='是否软删除'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='删除时间 (UTC)'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_withdrawal_records_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_withdrawal_records')),
    sa.UniqueConstraint('withdrawal_no', name=op.f('uq_withdrawal_records_withdrawal_no'))
    )
    op.create_index(op.f('ix_withdrawal_records_withdrawal_records_user_id'), 'withdrawal_records', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_withdrawal_records_withdrawal_records_user_id'), table_name='withdrawal_records')
    op.drop_table('withdrawal_records')
    # ### end Alembic commands ###
