"""add shipping templates and product weight

Revision ID: 36ab5d69d527
Revises: 01e8cf3d423c
Create Date: 2026-04-13 10:15:07.417650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '36ab5d69d527'
down_revision: Union[str, None] = '01e8cf3d423c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shipping_templates',
    sa.Column('id', sa.UUID(), nullable=False, comment='主键 (UUID v7)'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='模板名称'),
    sa.Column('pricing_method', sa.String(length=10), server_default=sa.text("'weight'"), nullable=False, comment='计价方式: weight(按重量) / piece(按件数)'),
    sa.Column('free_shipping_threshold', sa.Numeric(precision=10, scale=2), nullable=True, comment='满额包邮门槛（NULL=不设包邮，0=永远包邮）'),
    sa.Column('free_shipping_exclude_regions', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=True, comment='包邮排除的省份编码 ["650000","540000"]'),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='是否启用'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间 (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间 (UTC)'),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='是否软删除'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='删除时间 (UTC)'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shipping_templates'))
    )
    op.create_table('shipping_template_regions',
    sa.Column('id', sa.UUID(), nullable=False, comment='主键 (UUID v7)'),
    sa.Column('template_id', sa.UUID(), nullable=False, comment='所属运费模板 ID'),
    sa.Column('region_name', sa.String(length=50), nullable=False, comment='地区名称（如 江浙沪皖）'),
    sa.Column('province_codes', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False, comment='省份编码数组 ["310000","320000"]，空数组=其余地区'),
    sa.Column('first_unit', sa.Numeric(precision=10, scale=2), nullable=False, comment='首重(克)/首件(件)'),
    sa.Column('first_unit_price', sa.Numeric(precision=10, scale=2), nullable=False, comment='首重/首件费用'),
    sa.Column('additional_unit', sa.Numeric(precision=10, scale=2), nullable=False, comment='续重(克)/续件(件)'),
    sa.Column('additional_unit_price', sa.Numeric(precision=10, scale=2), nullable=False, comment='每续重/续件费用'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间 (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间 (UTC)'),
    sa.ForeignKeyConstraint(['template_id'], ['shipping_templates.id'], name=op.f('fk_shipping_template_regions_template_id_shipping_templates'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shipping_template_regions'))
    )
    op.create_index(op.f('ix_shipping_template_regions_shipping_template_regions_template_id'), 'shipping_template_regions', ['template_id'], unique=False)
    op.add_column('product_skus', sa.Column('weight', sa.Numeric(precision=10, scale=2), server_default=sa.text('0.00'), nullable=False, comment='重量（克），用于运费计算'))
    op.add_column('products', sa.Column('shipping_template_id', sa.UUID(), nullable=True, comment='运费模板 ID（NULL=包邮/虚拟商品）'))
    op.create_foreign_key(op.f('fk_products_shipping_template_id_shipping_templates'), 'products', 'shipping_templates', ['shipping_template_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_products_shipping_template_id_shipping_templates'), 'products', type_='foreignkey')
    op.drop_column('products', 'shipping_template_id')
    op.drop_column('product_skus', 'weight')
    op.drop_index(op.f('ix_shipping_template_regions_shipping_template_regions_template_id'), table_name='shipping_template_regions')
    op.drop_table('shipping_template_regions')
    op.drop_table('shipping_templates')
    # ### end Alembic commands ###
