"""add_user_social_sms_log_tables_and_password_nullable

Revision ID: 51c0e1e84482
Revises: bec27981acfa
Create Date: 2026-04-12 15:44:02.232671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '51c0e1e84482'
down_revision: Union[str, None] = 'bec27981acfa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sms_logs',
    sa.Column('id', sa.UUID(), nullable=False, comment='主键 (UUID v7)'),
    sa.Column('phone_code', sa.String(length=10), nullable=False, comment='手机区号 (如 +86)'),
    sa.Column('mobile', sa.String(length=20), nullable=False, comment='手机号码'),
    sa.Column('sms_type', sa.String(length=30), nullable=False, comment='短信用途类型'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='发送状态'),
    sa.Column('provider', sa.String(length=20), nullable=False, comment='短信服务商'),
    sa.Column('template_id', sa.String(length=50), nullable=True, comment='短信模板 ID'),
    sa.Column('content', sa.Text(), nullable=True, comment='发送内容摘要'),
    sa.Column('request_id', sa.String(length=100), nullable=True, comment='云平台请求流水号'),
    sa.Column('fail_reason', sa.String(length=500), nullable=True, comment='失败原因'),
    sa.Column('ip_address', sa.String(length=50), nullable=True, comment='请求方 IP'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间 (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间 (UTC)'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sms_logs'))
    )
    op.create_index(op.f('ix_sms_logs_sms_logs_mobile'), 'sms_logs', ['mobile'], unique=False)
    op.create_index(op.f('ix_sms_logs_sms_logs_sms_type'), 'sms_logs', ['sms_type'], unique=False)
    op.create_table('user_socials',
    sa.Column('id', sa.UUID(), nullable=False, comment='主键 (UUID v7)'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='关联用户ID'),
    sa.Column('platform', sa.String(length=50), nullable=False, comment='平台标识'),
    sa.Column('openid', sa.String(length=255), nullable=False, comment='三方唯一ID(OpenID)'),
    sa.Column('unionid', sa.String(length=255), nullable=True, comment='微信UnionID'),
    sa.Column('session_key', sa.String(length=255), nullable=True, comment='微信 session_key (加密密钥)'),
    sa.Column('nickname', sa.String(length=100), nullable=True, comment='三方平台昵称'),
    sa.Column('avatar', sa.String(length=500), nullable=True, comment='三方平台头像URL'),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='三方原始数据快照'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间 (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间 (UTC)'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_socials_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_socials')),
    sa.UniqueConstraint('platform', 'openid', name='uq_social_platform_openid')
    )
    op.create_index(op.f('ix_user_socials_user_socials_openid'), 'user_socials', ['openid'], unique=False)
    op.create_index(op.f('ix_user_socials_user_socials_platform'), 'user_socials', ['platform'], unique=False)
    op.create_index(op.f('ix_user_socials_user_socials_unionid'), 'user_socials', ['unionid'], unique=False)
    op.create_index(op.f('ix_user_socials_user_socials_user_id'), 'user_socials', ['user_id'], unique=False)
    op.alter_column('user_levels', 'commission_rules',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment="分佣规则 [{'rank':1,'first':'3%','second':'2%','other':'1'}]",
               existing_comment="分佣规则 [{'rank':1,'first':'3%','second':'2%','third':'1'}]",
               existing_nullable=True)
    op.alter_column('user_levels', 'reward_rules',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment="升级奖励规则 [{'rank':2,'first':'100','second':'50','other':'10'}]",
               existing_comment="升级奖励规则 [{'rank':2,'first':'100','second':'50','third':'10'}]",
               existing_nullable=True)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               comment='密码哈希值 (短信/小程序用户可为空)',
               existing_comment='密码哈希值')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               comment='密码哈希值',
               existing_comment='密码哈希值 (短信/小程序用户可为空)')
    op.alter_column('user_levels', 'reward_rules',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment="升级奖励规则 [{'rank':2,'first':'100','second':'50','third':'10'}]",
               existing_comment="升级奖励规则 [{'rank':2,'first':'100','second':'50','other':'10'}]",
               existing_nullable=True)
    op.alter_column('user_levels', 'commission_rules',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment="分佣规则 [{'rank':1,'first':'3%','second':'2%','third':'1'}]",
               existing_comment="分佣规则 [{'rank':1,'first':'3%','second':'2%','other':'1'}]",
               existing_nullable=True)
    op.drop_index(op.f('ix_user_socials_user_socials_user_id'), table_name='user_socials')
    op.drop_index(op.f('ix_user_socials_user_socials_unionid'), table_name='user_socials')
    op.drop_index(op.f('ix_user_socials_user_socials_platform'), table_name='user_socials')
    op.drop_index(op.f('ix_user_socials_user_socials_openid'), table_name='user_socials')
    op.drop_table('user_socials')
    op.drop_index(op.f('ix_sms_logs_sms_logs_sms_type'), table_name='sms_logs')
    op.drop_index(op.f('ix_sms_logs_sms_logs_mobile'), table_name='sms_logs')
    op.drop_table('sms_logs')
    # ### end Alembic commands ###
