"""feat: shopping carts domain

Revision ID: 000b8363728f
Revises: 5c90877bc4e4
Create Date: 2026-04-12 22:24:15.566604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '000b8363728f'
down_revision: Union[str, None] = '5c90877bc4e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart_items',
    sa.Column('id', sa.UUID(), nullable=False, comment='主键 (UUID v7)'),
    sa.Column('user_id', sa.UUID(), nullable=True, comment='实名归属（与 anonymous_id 必有一填）'),
    sa.Column('anonymous_id', sa.String(length=128), nullable=True, comment='游客设备的唯一特征指纹'),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('sku_id', sa.UUID(), nullable=True, comment='如果商品带变体必选'),
    sa.Column('quantity', sa.Integer(), nullable=False, comment='件数'),
    sa.Column('selected', sa.Boolean(), nullable=False, comment='UI 选定结算状态'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间 (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间 (UTC)'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_cart_items_product_id_products'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sku_id'], ['product_skus.id'], name=op.f('fk_cart_items_sku_id_product_skus'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_cart_items_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cart_items'))
    )
    op.create_index('ix_cart_items_user_or_anon', 'cart_items', ['user_id', 'anonymous_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_cart_items_user_or_anon', table_name='cart_items')
    op.drop_table('cart_items')
    # ### end Alembic commands ###
