"""feat: user product views

Revision ID: 5c90877bc4e4
Revises: a0a1a71326eb
Create Date: 2026-04-12 22:06:07.214986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c90877bc4e4'
down_revision: Union[str, None] = 'a0a1a71326eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_views',
    sa.Column('id', sa.UUID(), nullable=False, comment='主键 (UUID v7)'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='访客 ID'),
    sa.Column('product_id', sa.UUID(), nullable=False, comment='被浏览商品的 SPU ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间 (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间 (UTC)'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_views_product_id_products'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_product_views_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_views')),
    sa.UniqueConstraint('user_id', 'product_id', name='uq_product_views_user_product')
    )
    op.create_index(op.f('ix_product_views_product_views_user_id'), 'product_views', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_views_product_views_user_id'), table_name='product_views')
    op.drop_table('product_views')
    # ### end Alembic commands ###
